### ISSUE TITLE
Collect real data for Examples

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#11]
Let's collect some _actual_ data that we can use as examples for the BEP001.

One candidate already is Chris G's 7T dataset:
https://openneuro.org/datasets/ds000113

Wietske van der Zwaag's 3D EPI MP2RAGEs:
https://www.sciencedirect.com/science/article/pii/S2352340918308825

I am most likely to also share some ME-MP2RAGE data.

**Comment by Gilles86** [comment]
Does anyone have some MPM or MT-data to share?

**Comment by KirstieJane** [comment]
There's this openly available hRMI (MPM) data: https://github.molgen.mpg.de/hMRI-group/Toolbox/wiki/HmriDemoDataset

**Comment by Gilles86** [comment]
Bit of a mundane question, but: where should we put these example datasets? Github tends to not work very well with large data files. What is a good alternative?

**Comment by agahkarakuzu** [comment]
I think [Open Science Framework](https://osf.io/) is a good option.

**Comment by agahkarakuzu** [comment]
@Gilles86 happy to share example datasets for the (remaining) methods I listed [here](https://docs.google.com/spreadsheets/d/1awzGVflxXiWtzeLVOH5XI8Bar2ND9759yZxsK3stCzc/edit?usp=sharing). I also created a [project on OSF](https://osf.io/k4bs5/), I can transfer its ownership to you and invite collaborators if everyone is OK to upload here.

**Comment by Gilles86** [comment]
> @Gilles86 happy to share example datasets for the (remaining) methods I listed [here](https://docs.google.com/spreadsheets/d/1awzGVflxXiWtzeLVOH5XI8Bar2ND9759yZxsK3stCzc/edit?usp=sharing). I also created a [project on OSF](https://osf.io/k4bs5/), I can transfer its ownership to you and invite collaborators if everyone is OK to upload here.

Would be great!

**Comment by KirstieJane** [comment]
Here's an osf repository that @emdupre created for the `tedana`:tada: project: https://osf.io/bpe8h/

Seems like a similar idea for BEP001 examples would be great.

**Comment by akhanf** [comment]
I can contribute a session with MP2RAGE,  Sa2RAGE, multi echo GRE (mag, phase)

**Comment by KirstieJane** [comment]
Assigned to @Gilles86, @tiborauer & @christophephillips to add their data to an osf project.

@agahkarakuzu to give write access to already existing OSF project: https://osf.io/k4bs5. 😸

**Comment by satra** [comment]
we currently have a test-retest single subject MPM dataset that can be added as well.

**Comment by agahkarakuzu** [comment]
I started pushing some example data to [OSF](https://osf.io/k4bs5/). Here is my checklist for the examples I can collect: 

- [x] VFA 
- [ ] MTS
- [ ] MESE (MWFmap)
- [ ] B1DAM
- [ ] IRT1 
- [ ] MTR 

My examples wont be "complete datasets", but would  make a decent demonstration as a starting point. 

@Gilles86 will bring in examples for  
- [ ] MP2RAGE 
- [ ] ME-MP2RAGE 

Side note, for ME-MP2RAGE please see the [`qMRI applications that can be derived from an existing grouping suffix`](https://github.com/bids-standard/bep001/blob/indexable_metadata/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md) subsection. I think `ME-MP2RAGE` worths being listed there, and other qMRI applications that can use an existing suffix but can create new use cases by alternations to the additional parameters. That table eventually should put things in better context on the relevance between suffixes and various qMRI applications.

**Comment by agahkarakuzu** [comment]
@lazaral I saw that you created a new project in OSF for MPM data (https://osf.io/zthwr/). I will soon add all the people on `zthwr` to [https://osf.io/k4bs5/](https://osf.io/k4bs5/). We can keep all the examples in one place, would make our life easier.  Would you mind uploading your examples dataset to `k4bs5` ? 

> Edit: 

I've just added you and C. Phillips to the OSF page for BEP001,  you have read/write access.

**Comment by lazaral** [comment]
Yes that's a great idea - thank you @agahkarakuzu !

**Comment by ChristophePhillips** [comment]
Thanks @agahkarakuzu !
I've been playing with the [hMRI toolbox](http://hmri.info) [example dataset](https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ) and will try to push them there, as soon as I've got an 'acceptable BIDSified version' of them. :-)
