### ISSUE TITLE
Implement BEP001 in pybids

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#12]
It would be good if we implement BEP001 in [`pybids`](https://github.com/Gilles86/pybids/tree/BEP001) before release, so people (e.g., me) can easily develop pipelines etc.

I made a first go here:
https://github.com/Gilles86/pybids/tree/BEP001

**Comment by KirstieJane** [comment]
Hey @Gilles86 - pybids has been undergoing a BIG refactor recently. How much do you want to work on this now vs wait until they (and the specification) are stable?
