### ISSUE TITLE
Add new key `part` for magnitude and phase maps

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#2]
Discussion in the google doc:

https://docs.google.com/document/d/1QwfHyBzOyFWOLO4u_kkojLpUhW0-4_M7Ubafu9Gf4Gg/edit?disco=AAAABql0bLg

Need to get MH to sign off on incorporating it but decision in July meeting was to add this new key.

**Comment by Gilles86** [comment]
Addressed in pull request https://github.com/bids-standard/bep001/pull/13/
