### ISSUE TITLE
Explain `_suffix` has _some_ flexibility

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#27]
The text should make clear that there are recommendations for standard suffixes for standard sequences (MP2RAGE, FLASH, T1w), but depending on context, one can change the suffix. This is to make sure the standard remains _extensible_.

**Comment by chrisgorgo** [comment]
As with other suffixes in the spec I would recommend requiring users to pick one suffix from the list instead of allowing any suffix. In case of new sequences and file type a PR should be sent to bids-specification with a simple addition to the table of suffixes.

**Comment by agahkarakuzu** [comment]
Resolved [here](https://github.com/agahkarakuzu/bep001/pull/3 ).
