### ISSUE TITLE
Rename sequence label to modality label

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#3]
To be discussed in August call.

**Comment by Gilles86** [comment]
Has this now been agreed upon or not? Not clear to me from August notes.

**Comment by KirstieJane** [comment]
There's a table in BIDS that uses `modality_label` already: https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html

**Comment by Gilles86** [comment]
In the latest version of pybids, this is actually called a `suffix`.
https://github.com/bids-standard/pybids/blob/master/examples/pybids%20tutorial.ipynb

**Comment by Gilles86** [comment]
See https://github.com/bids-standard/bep001/commit/48a784b349b5f24c3acb3de5b407fe9c1333f7ac

**Comment by Gilles86** [comment]
Adressed in pull request https://github.com/bids-standard/bep001/pull/13/
