### ISSUE TITLE
Agenda & Minutes from March call

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#31]
* Update on the big merges that @KirstieJane and @Gilles86 did this morning 😬 💪 🚀 
* Look through issue list
  * Close those that are done
  * Assign those that are not!

**Comment by tiborauer** [comment]
Where is the list with the action points?

**Comment by KirstieJane** [comment]
***Notes from call on March 20***

* Update on merges that @KirstieJane & @Gilles86 did on 20 March
  * There are lots of different branches and it's kinda confusing....so we've merged some of the changes that we agree on into the master branch
  * Agreed changes to be documented in [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md)

Future tasks:

* Update [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) with the changes that @agahkarakuzu made in #30 --- action @agahkarakuzu 
  * Key discussion had in the call about why we have justified collecting different scans together under one suffix (eg: `MP2RAGE` and `MPM`)
* There are a couple of inconsistencies with the examples -- specifically that `FLASH` is currently used as a suffix --- action @alazari 
  * MPM examples use a bunch of different suffices:
    * Rename `sub-01_echo-1_part-mag_MTw.nii.gz` --> `sub-01_echo-1_part-mag_aqc-MTon_MPM.nii.gz`
    * Rename `sub-01_echo-1_part-mag_PDw.nii.gz` --> `sub-01_echo-1_part-mag_aqc-MToff_MPM.nii.gz`
    * Rename `sub-01_echo-1_part-mag_T1w.nii.gz` --> `sub-01_echo-1_part-mag_aqc-T1w_MPM.nii.gz`
 * Outputs for `MPM` processing should be in a `derivatives` folder.
* Need to add a little more explanation to the `indexable_metadata` section: https://github.com/bids-standard/bep001/issues/26#issuecomment-474945579 --- @agahkarakuzu 
* Need to add to the specification something about being able to symlink derivatives files to raw --- @KirstieJane 
  * Specifically to allow outputs to be used with current BIDS-Apps.
  * In the future, hopefully the BIDS-Apps will be able to take inputs _from_ the derivatives, so this linking is a band-aid to help qMRI researchers get into the BIDS-App ecosystem, not a long term plan 😄 
* Read through the draft specification looking for where examples can be added to make things clearer --- @tiborauer
  * Useful google doc from @agahkarakuzu: https://docs.google.com/document/d/1HfCjPKCXqTckB0OPs-Py06yY2gPYaFGc0sFTPB74fEA/edit?usp=sharing
* Tidy up the issues and fix a few "little" points --- @Gilles86 

***Action for all***: If you make any changes, please update the [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) document so that when we create a PR to the main specification, we can explain all the different changes we've made 😄 

---

Next call: Wednesday 17 April at 6pm CEST / 5pm BST / 12noon EDT / 9am PDT ✨ 🚀 🌟

**Comment by ChristophePhillips** [comment]
Should we also plan a meeting at next HBM in Rome ?
If a few of us are around, it's always nice and efficient to catch up face-to-face, discuss remaining issues, maybe look at some data, etc.

**Comment by Gilles86** [comment]
> Should we also plan a meeting at next HBM in Rome ?
> If a few of us are around, it's always nice and efficient to catch up face-to-face, discuss remaining issues, maybe look at some data, etc.
