### ISSUE TITLE
Agenda for April call | Wed 17 6pm / 5pm / 12noon / 9am

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#32]
***Next dev call: Wednesday 17 April at 6pm CEST / 5pm BST / 12noon EDT / 9am PDT***

All welcome, please see BIDS mailing list for zoom link (or ping @KirstieJane!)

## Agenda

This agenda is built from the March call (#31) minutes. @KirstieJane has had a little rearrange to hopefull make the meeting flow sensibly 😄 

### Indexable metadata -- #26 

*From last month's action list*
- [x] Need to add a little more explanation to the `indexable_metadata` section: https://github.com/bids-standard/bep001/issues/26#issuecomment-474945579 --- @agahkarakuzu 

👉 @agahkarakuzu merged PR #37  🚀 ✨ 💯 

- [ ] Not yet done - add to [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) file 😭 
  * @KirstieJane has kinda started in #25 (bad git management rather than on purpose) see [here](https://github.com/bids-standard/bep001/pull/25/files#diff-080f3523f5a2c25654c43f53d0e8091eR12) but it isn't complete.

### Proposed changes to specification -- #41

- [ ] Update [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) with the changes that @agahkarakuzu made in #30 --- action @agahkarakuzu 

* Key discussion had in the call about why we have justified collecting different scans together under one suffix (eg: `MP2RAGE` and `MPM`)

### Update examples -- issue #34 

- [ ] There are a couple of inconsistencies with the examples -- specifically that `FLASH` is currently used as a suffix --- action @alazari 

* MPM examples use a bunch of different suffices:
  * Rename `sub-01_echo-1_part-mag_MTw.nii.gz` --> `sub-01_echo-1_aqc-MTon_part-mag_MPM.nii.gz`
  * Rename `sub-01_echo-1_part-mag_PDw.nii.gz` --> `sub-01_echo-1_aqc-MToff_part-mag_MPM.nii.gz`
  * Rename `sub-01_echo-1_part-mag_T1w.nii.gz` --> `sub-01_echo-1_aqc-T1w_part-mag_MPM.nii.gz`
* Outputs for `MPM` processing should be in a `derivatives` folder.

See PR #38 
* Comment from @KirstieJane on https://github.com/bids-standard/bep001/pull/38#issuecomment-483396245
  * Linked PR: https://github.com/lazaral/bep001/pull/1

### Symlink - issue #8

- [ ] Need to add to the specification something about being able to symlink derivatives files to raw --- @KirstieJane 
  * Specifically to allow outputs to be used with current BIDS-Apps.
  * In the future, hopefully the BIDS-Apps will be able to take inputs _from_ the derivatives, so this linking is a band-aid to help qMRI researchers get into the BIDS-App ecosystem, not a long term plan 😄 

* Current WIP #25 - this is just a bit of a mess because I have too many other files in this branch 😬 
  * But if anyone can reveiw what I've written for the [common principles](https://github.com/bids-standard/bep001/pull/25/files#diff-ba564f153b960d803d493fe37fbbb34eR112) section that would be great!

### Add examples to specification

- [ ] Read through the draft specification looking for where examples can be added to make things clearer --- @tiborauer
  * Useful google doc from @agahkarakuzu: https://docs.google.com/document/d/1HfCjPKCXqTckB0OPs-Py06yY2gPYaFGc0sFTPB74fEA/edit?usp=sharing

### Tidy up

- [ ] Tidy up the issues and fix a few "little" points --- @Gilles86 

### Looking forwards

What are the next steps we need to take?

**Comment by tiborauer** [comment]
Regarding the examples, the current version contains a template
`sub-<participant_label>[_ses-<session_label>][_<indexable_metadata>-<index>][_acq-<label>][_part-<mag/phase>][_ce-<label>][_rec-<label>][_run-<index>]_<suffix>.nii.gz`, 
so the MPM example should be:
- `sub-01_echo-1_acq-MTon_part-mag_MPM.nii.gz`
- `sub-01_echo-1_acq-MToff_part-mag_MPM.nii.gz`
- `sub-01_echo-1_acq-T1w_part-mag_MPM.nii.gz`
(i.e. "acq" before "part")

**Comment by KirstieJane** [comment]
Hey @tiborauer - would you mind opening a new issue? I can link to it in the agenda. This thread might get rather overwhelmed if we all comment here....

**Comment by KirstieJane** [comment]
Oh wait - sorry - it's my text that's wrong.... I'll fix that. 

(update, fixed!)

**Comment by tiborauer** [comment]
Done! See #34

**Comment by Gilles86** [comment]
Let's also talk about a possible OHBM meeting in Rome.

**Comment by Gilles86** [comment]
We need to talk about where B1 fieldmap should go and what their filename should look like.

**Comment by KirstieJane** [comment]
Hey folks - I'm taking minutes here - come and join me :wink: 
https://hackmd.io/MRTYVroETa2aKvwVjNaKGg

**Comment by KirstieJane** [comment]
Closing as I _hope_ I've captured all the points in #47
