### ISSUE TITLE
FLASH vs MEGRE vs GRE

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#42]
We need to clarify in the specification the difference between using the `_FLASH` suffix and the `_MEGRE`  suffix.

We're leaving `_FLASH` in the specification to maintain backwards compatibility but we recommend that it is superceded by the vender non-specific `_MEGRE` suffix (multi-echo gradient echo) suffix.

Note that `_GRE` is probably going to be used for a `_T1w`, `_T2star` or `_PDw` or one of the other suffices which is why we aren't adding it.

**Comment by KirstieJane** [comment]
I'm not confident that this discussion is captured in the text at the moment. I think we need this added to the `ProposedChangesInSpecification.md` somewhere and possibly expanded up on in the specification a little more clearly.

**Comment by Gilles86** [comment]
See Pull #58
