### ISSUE TITLE
Update text in specification for field map

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#44]
The section in the main specification that describes field maps is written for fMRI folks by fMRI folks 😉 

This section needs some re-arranging so that it clearly describes a broader use of field maps.

We also need to be clear - through using a few examples - where the field maps need to go (derivatives or raw folders?)
  * What processing is done to create these maps? What additional json metadata do we need to include?

**Comment by Gilles86** [comment]
See pull request #48.

**Comment by KirstieJane** [comment]
This PR looks great merging!

@agahkarakuzu is assigned to add in a few additional field maps to the table.
