### ISSUE TITLE
What metadata fields do we want to request for the specification

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#45]
I have such a list from the last time I dived into the code:

    FieldnamesOriginal	FieldnamesBIDS	                Scaling
    RepetitionTime	        ExcitationRepetitionTime	1
    EchoTime	        EchoTime	                1
    FlipAngle	        FlipAngle	                1
    B1mapNominalFAValues	B1mapNominalFAValues	        1
    B1mapMixingTime	        MixingTime	                1
    epiReadoutDuration	epiReadoutDuration	        1
    PhaseEncodingDirectionSign	PhaseEncodingDirectionSign	NaN
    ScanningSequence	ScanningSequence	        NaN
    SequenceName	        SequenceName	                NaN
    ProtocolName	        ProtocolName	                NaN
    RFSpoilingPhaseIncrement	RFSpoilingPhaseIncrement	1
    spoilingGradientMoment	spoilingGradientMoment	       1
    spoilingGradientDuration	spoilingGradientDuration	1

These are a bit outdated but can be easily updated, such that the DICOM-to-NIFTI conversion produces the right BIDS-fields.
Then variable names can easily be updated in the main code, as number crunching routines typically use shorter names and simply 'import' the required parameters at the beginning.

**Comment by KirstieJane** [comment]
There are some already in this version (thanks @agahkarakuzu)

I think this needs to be added to the [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) file.

And maybe @christophephillips can review the changes and see if there are any others we need to add.

**Comment by KirstieJane** [comment]
This is related to #56.

**Comment by agahkarakuzu** [comment]
Please see 69f8d5857ca8288deea5cbad78fbe513243c2f2b for the additions I made for metadata.
