### ISSUE TITLE
Make sure that all the names in our examples folder conform to spec and make sense

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#46]
Can we change the names of the example data sets to make it clear why they're there?

I think @lazaral had a markdown file describing them a little so maybe you can take this one on?

* Clearer names
* Useful information in the data set description json file
* Make sure the derivatives folders have correct pipeline names

**Comment by lazaral** [comment]
Sure, that sounds great! Will do it this week so people have a chance to have a final look at the examples before the next meeting.

**Comment by KirstieJane** [comment]
Fantastic! Thank you!

**Comment by lazaral** [comment]
@KirstieJane I had a first go at this - except for the data set description json file. It would definitely be useful to add more information there but not sure exactly where to start - do you have any suggestions?

**Comment by KirstieJane** [comment]
Fab! Thank you @lazaral!! Ping me the link to your branch with changes and I'll see if I can add an example :)

**Comment by KirstieJane** [comment]
Nevermind! Found the changes in #38
