### ISSUE TITLE
Agenda for May call | Wed 15 6pm / 5pm / 12noon / 9am

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#47]
***Next dev call: Wednesday 15 May at 6pm CEST / 5pm BST / 12noon EDT / 9am PDT***

All welcome, please see BIDS mailing list for zoom link (or ping @KirstieJane!)

## Agenda

The following points are put in place by @KirstieJane after the March call....they might move around as we develop and discuss the extension 😸 

### Document merged changes

There are a few changes that are already merged to `master` but that aren't reflected in the [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) file.

- [ ]  `indexable metadata`  merged in PR #37 but issue #26 open until the PCTS doc is updated
- [ ] there are a few changes merged in PR #30 but not captured in the PCTS doc
  * Discussion about why we have justified collecting different scans together under one suffix (eg: `MP2RAGE` and `MPM`) needs to be added....for example.

### Update the examples

We have some nice example folder structures at the moment, but there are a couple more tasks that should be done. See #34 & #35, #46.

General driving principle is that for each new concept in the specification we have an example in the text (and maybe as a dataset?)

There's the open issue #11 which hasn't moved forwards in a while - lets see where that goes.

### Field maps

We need to update the specification (and maybe some of the examples - the files might be in the wrong folders) to generalise the use of field maps. See #44 

### Symbolic links

Need to add to the specification something about being able to symlink derivatives files to raw. See #25 
  * Specifically to allow outputs to be used with current BIDS-Apps.
  * In the future, hopefully the BIDS-Apps will be able to take inputs _from_ the derivatives, so this linking is a band-aid to help qMRI researchers get into the BIDS-App ecosystem, not a long term plan 😄 

### Timeline

It would be GREAT to get a PR open to the main specification before OHBM. Documenting what we have done (and why we have done it) is one of the big steps in getting there.... 💪 Keep up the hard work 🏋️ 🏋️‍♀️ 👾 

We'll plan to meet on Wednesday 29 May at 4pm CEST / 3pm BST / 10am EDT / 7am PDT and also in person at OHBM in the Open Science Room. Stay tuned 🚀

**Comment by nicholst** [comment]
I can't make this call but I wanted to ping a related issue I posted on the BIDS main repo:

"PDT2 anatomical modality: Recommendations and potential use of _echo"
https://github.com/bids-standard/bids-specification/issues/223 

Mainly just looking for recommendations of how to name PD and T2 echo pairs when they've been glued together with the `_PDT2` modality label.

**Comment by agahkarakuzu** [comment]
@nicholst `_PDT2` was there as a placeholder for a while, it is still untouched. Thank you for the reference, I will read this.

**Comment by KirstieJane** [comment]
Thanks @nicholst! I'm closing this issue as we have had the call.

I think @Gilles86 is going to reply to your question at bids-standard/bids-specification#223 though. If it doesn't make sense then please open a new issue to discuss. I think the answer is related to #50 which contains a link to a WIP 😄
