### ISSUE TITLE
Transfer ownership to new bids-standard organisation

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#5]
Hi @chrisfilo - please could you transfer this repository into the [`bids-standard`](https://github.com/bids-standard/) organisation? Then we're all nicely lined up with the other repositories.

If you'd like to re-name it to `bep001` that's totally fine with me (and I don't think @Gilles86 will be super mad...although I've tagged him now to double check!)

**Comment by chrisgorgo** [comment]
I could do that or I could give you write access to https://github.com/bids-standard/bids-specification and bep001 issues could be managed via a dedicated `bep001` tag and (optionally) a [project board](https://help.github.com/articles/tracking-the-progress-of-your-work-with-project-boards/) (which spans all repos in the organization - so you could mix spec and validator issues).

What would you prefer?

**Comment by KirstieJane** [comment]
Sorry for the slow reply @chrisfilo! I'm pretty overwhelmed with all the notifications in the bids-specification repo so it would be nice to keep this one separate as we have the various discussions 😄 

Would you mind transferring us to `bids-standard` please? (or let me know if I have that power!)

**Comment by chrisgorgo** [comment]
You should have the power (unless some permissions on INCF side are missing). Please let me know if you run into issues.

It would be great if the repo was renamed to `bep006` for consistency.

PS It might be good to start planning turning the Google doc into Markdown and opening a PR at `bids-specification`

**Comment by KirstieJane** [comment]
Thanks @chrisfilo - I'll give it a bash.

Was the `bep006` a typo? Are we no longer `bep001`?

Totally fine with changing to lowercase whichever number we are!

**Comment by chrisgorgo** [comment]
yes bep001
Best,
Chris

**Comment by KirstieJane** [comment]
Phew! I was super confused for a minute there 👾

**Comment by KirstieJane** [comment]
Done! ✅
