### ISSUE TITLE
Be precise about B1plusmap, B1minusmap and B1map.

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#51]
Hey, 

I notice that there are some inconsistencies in the spec right now. So in general, people seem to use `B1map` and `B1plusmap` interchangeably. But for the MPM examples, we use `B1minusmap`. What should we do here? Replace everything with `B1plusmap`?

-Gilles

**Comment by agahkarakuzu** [comment]
So the options would be: 
1. `B1map` and `B1minusmap` 
2.  `B1map` and `Sensmap` 
3.  `B1plusmap` and `B1minusmap` 
4.  (`B1map` + `B1plusmap`) and `B1minusmap` 

First off, would 4 be possible? I've almost never seen anyone who uses `B1map` to refer to `B1minusmap`. Can we somehow accommodate that interchangeability in the spec? I know this is not ideal, but don't know which one would be more expensive. Changing everything or having two labels pointing to the same entity?

**Comment by Gilles86** [comment]
I think B1map is not in the spec yet. Only in some of our other examples.
So I really prefer option 3.

Stupid qustion:are the B1minusmaps in the MPM examples really B1 _minus_
maps?

Let's discuss this in the meeting later.

**Comment by agahkarakuzu** [comment]
> Stupid qustion:are the B1minusmaps in the MPM examples really B1 _minus_
maps?

Need to go back to method paper to find out. 

> Let's discuss this in the meeting later.

Cool!

**Comment by agahkarakuzu** [comment]
+1 on option 3 as well then.

**Comment by agahkarakuzu** [comment]
From the original paper:

> The MPM comprised three multi-echo 3D FLASH (fast low angle shot) scans, one RF transmit field map and one static magnetic (B0) field map scan (Weiskopf et al., 2011).

The h-MRI toolbox allows generation of a `B1minus` map (N4ITK kind of bias correction) if inputs for B1map fitting (3D segmented EPI) are not provided by user. At 3T, B1+ and B1- are fairly comparable, but not quite sure how processing advances in that case.

**Comment by Gilles86** [comment]
OK, but a standard MPM protocol then apparently includes a B1 plus map
right?

**Comment by KirstieJane** [comment]
@christophephillips - can you answer this question? What is expected for the MPM protocol?

**Comment by lazaral** [comment]
As far as I understand MPM/hMRI uses both transmit and receive fields (although if I’m not wrong Weiskopf 2013 only used B1+, B1- was added after and is now part of hMRI in Tabelow 2019). The MPM protocol I use definitely includes both. I’d love to hear confirmation from actual MPM experts like @ChristophePhillips  though!
