### ISSUE TITLE
Relationship of new modality labels to existing for proton density acquisitions

### ISSUE THREAD

**Issue by nicholst** [bids-standard/bep001#52]
Jumping in here without having been involved much... hope this is isn't annoyingly obvious/redundant...

In reviewing bep001's [04-modality-specific-files/01-magnetic-resonance-imaging-data.md](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md) I noticed there is

Name | _suffix | Description
-- | -- | --
Proton density weighted images | PDw | Denotes images with predominant PD contrast.

while in the current standard we have in [04-modality-specific-files/01-magnetic-resonance-imaging-data.md](https://github.com/bids-standard/bids-specification/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md) we currently have 

Name | _suffix | Description
-- | -- | --
Proton density | PD |  

Is the proposal to remove `PD` and replace it with `PDw`?  While that is most logical, it represents a non-backwards compatible change; also, it suggests that current modality label `PDT2` should also be revised to `PDT2w` (or `PDwT2w`?).

As this looks rather mature, seems sensible to think about how this will merge with the existing standard.

**Comment by Gilles86** [comment]
> Is the proposal to remove PD and replace it with PDw?

Yes. We are going to make a 'legacy'-part of the big table where we put some the suffixes that are already in the spec but we recommend not to use anymore.

See https://github.com/bids-standard/bep001/issues/55
