### ISSUE TITLE
Add T2starw suffix

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#54]
For legacy and logical purposes it makes sense to add a `T2starw` suffix. This will push `T2star` into the legacy section of `suffix` table (see #55) and hopefully make the standard a little more internally consistent.

Assigned to @Gilles86

**Comment by agahkarakuzu** [comment]
@Gilles86 I made some changes to the table on my `indexable_metadata` branch. Feel free to cherrypick 5ee5c96a75690e3e59a2b9663dd5eb941217ba0f.
