### ISSUE TITLE
Check if current standard accomodated MPM/hMRI required metadata

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#56]
Action for @christophephillips to map the metadata that is required for the `hmri` toolbox into the BEP001 recommendations and to check whether we're all covered.

**Comment by ChristophePhillips** [comment]
Here are what I found in term of metadata for the MPM sequence 

## Specific  acquisition parameters

This list the parameters as being used by the [hMRI toolbox]([http://hmri.info](http://www.hmri.info/)), as of September 2019.

---

| Fieldnames queried by the hMRI toolbox |Fieldnames for BIDS | Already existing in BIDS? | Description/comments |
| ---- | ---- | ---- | ---- |
| **GENERAL** | | | |
| RepetitionTime | RepetitionTimeExcitation	| y |  |
| EchoTime | EchoTime | y |  |
| FlipAngle | FlipAngle | y |  |
| **NAMING** | | | |
| ScanningSequence | ScanningSequence | y | |
| SequenceName | SequenceName | y | |
| ProtocolName | ProtocolName | N | What does it correspond to exactly? Add def in BIDS? |
| ManufacturerModelName | ManufacturerModelName | y |  |
| **RF SPOILING** | | | |
| RFSpoilingPhaseIncrement | SpoilingRFPhaseIncrement | y |  |
| spoilingGradientMoment | SpoilingGradientMoment | y | |
| spoilingGradientDuration | SpoilingGradientDuration | y | |
| **B1 MAPPING** | | ||
| B1mapNominalFAValues | B1mapNominalFAValues | N | Extend `FlipAngle` with `NominalFlipAngle`? |
| B1mapMixingTime | MixingTime | N | Anything close? |
| epiReadoutDuration | epiReadoutTime | N | Is this equivalent to `TotalReadoutTime`? |
| PhaseEncodingDirectionSign | PhaseEncodingDirectionSign | N | Same as `SliceEncodingDirection`? |
| BandwidthPerPixelRO | BandwidthPerPixelRO | N | Seems linked to `EffectiveEchoSpacing` but? |
| PELinesPAT | PELinesPAT | N | ?? |
| NumberOfMeasurements | NumberOfMeasurements | N | ?? |
| **OTHERS** ||||
| RepetitionTimes | RepetitionTimesExcitation | N | See extra 's', used(?) in case multiple TRs are passed -> not standard BIDS anyway |

Comments:
- **NAMING**. There are many other fields regarding the hardware, see the **Scanner hardware** section of [this file](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#scanner-hardware) and the same goes for the **Sequence Specifics**.
- **RF SPOILING**. There are 2 more fields *SpoilingState* (`true`/`false`) and *SpoilingType* (`RF`, `GRADIENT`, or `COMBINED`), see bottom of **Sequence Specifics** [section](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#sequence-specifics).
- **B1 MAPPING**. These are not part of the current proposal and would have to be added. What is missing is a clear definition of each of these parameters...

**Comment by tiborauer** [comment]
- What is `ProtocolName` for?
- Does B1 map has 'normal' `FlipAngle` apart from `NominalFlipAngle`? How do you get `NominalFlipAngle`?
- How do you get `B1mapMixingTime`?
- How do you get `epiReadoutDuration`? `TotalReadoutTime` "is NOT the actual, physical duration of the readout train", if that is what you after.
- Is `PhaseEncodingDirectionSign` the same as `PhaseEncodingDirectionPositive` (in Siemens)? I am not sure whether it is available in DICOMs from other vendors.
- How do you get `BandwidthPerPixelRO`? I know about `BandwidthPerPixelPhaseEncode`, but it is along the other axis.
- What is `PELinesPAT`?
- What is `NumberOfMeasurements`?

**Comment by tiborauer** [comment]
Is `PhaseEncodingDirectionSign` the same as `PhaseEncodingDirectionPositive` (in Siemens)? I am not sure whether it is available in DICOMs from other vendors.

**Comment by KirstieJane** [comment]
Some notes from the conversation on 9 October.

* Can we match up each of these metadata fields to the dicom tags that they allign to?
  * We have an action going forwards to harmonise the current terms with the additional metadata terms. Plan is to clearly define the needed information first.
* Are there some metadata fields listed above that are actually collections of other metadata from the scanner? We decided that it makes most sense to define the fields that come off the scanner rather than calculated ones.
  * Search for the "Method-specific priority levels for qMRI metadata" and "qMRI applications that can be derived from an existing grouping suffix" sections in the https://github.com/bids-standard/bep001/blob/indexable_metadata/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md file
* It would be great to be clear about which of the metadata fields are _required_ vs _desirable_.

**Comment by ChristophePhillips** [comment]
I have updated the list of parameters, see [here](https://github.com/CyclotronResearchCentre/hMRItbx_SampleDS_BIDS/blob/master/MPM_parameter_list.md), for the MPM sequence. 

Good news: most of them fit with the current BEP001, only a handful should/could be added. And since BIDS relies on the 80/20 Pareto's principe, this may not be needed actually.

The description of the field maps, or raw data leading to the estimation of these field maps to be more precise, remains open to discussion at the moment, cf #51, #67, #73, #80.

**Comment by agahkarakuzu** [comment]
Thank you @ChristophePhillips! I was just updating the MPM description on the suffix table and adding a link to the protocols suggested by hMRI (https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ) :)
