### ISSUE TITLE
Agenda for (second) May call | Wed 29 4pm / 3pm / 10noon / 7am

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#57]
***Next dev call: Wednesday 29 May at 4pm CEST / 3pm BST / 10am EDT / 7am PDT***

All welcome, please see BIDS mailing list for zoom link (or ping @KirstieJane!)

## Agenda

The following points are put in place by @KirstieJane after the call on 15 May....they might move around as we develop and discuss the extension 😸 

### Document merged changes: @KirstieJane & @agahkarakuzu

There are a few changes that are already merged to `master` but that aren't reflected in the [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) file.

- [ ]  `indexable metadata`  merged in PR #37 but issue #26 open until the PCTS doc is updated
- [x] there are a few changes merged in PR #30 but not captured in the PCTS doc
  * Discussion about why we have justified collecting different scans together under one suffix (eg: `MP2RAGE` and `MPM`) needs to be added....for example.

### Update the examples: @lazaral, @tiborauer, @christophephillips & @Gilles86 

General driving principle is that for each new concept in the specification we have an example in the text (and maybe as a dataset?)

#### Empty files correctly named: @lazaral

Issues #34 & #46.

#### Real data in BIDS format: @tiborauer, @christophephillips & @Gilles86 

Issue #11.

### List of metadata terms

Do the metadata terms that we have listed contain the information needed to run the processing pipelines? Are there any missing?

#### Run hmri toolbox on BIDS formatted data: @christophephillips

Specifically, can we run the hmri toolbox on BEP001 formatted data? (And get out BEP001 formatted data!)

### Field maps: @agahkarakuzu 

Expand definition of field maps in specification. Issue #44.

### Symbolic links: @KirstieJane 

Need to add to the specification something about being able to symlink derivatives files to raw. See #25 
  * Specifically to allow outputs to be used with current BIDS-Apps.
  * In the future, hopefully the BIDS-Apps will be able to take inputs _from_ the derivatives, so this linking is a band-aid to help qMRI researchers get into the BIDS-App ecosystem, not a long term plan 😄 

### Timeline

It would be GREAT to get a PR open to the main specification before OHBM. Documenting what we have done (and why we have done it) is one of the big steps in getting there.... 💪 Keep up the hard work 🏋️ 🏋️‍♀️ 👾 

We'll plan to meet in person at OHBM in the Open Science Room: https://github.com/ohbm/OpenScienceRoom2019/issues/18

**Comment by ChristophePhillips** [comment]
Hi,
I might be a bit late for the meeting.
Moreover since I'm running behind the clock I haven't sufficiently investigated the MPM data set to provide a nice feedback on how it BIDSifies, if parameters are missing or not matching definitions in BIDS, etc. Sorry about that !
At the latest, I'll do that during the Hackathon in Rome.
