### ISSUE TITLE
Enforce phase images within certain range?

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#6]
I think it would be good to enforce within BIDS that phase images are always constrained to (0, 2pi] radians (including 0, excluding 2 pi). This makes it easier to, e.g., fit qMRI models. What do you guys think?

**Comment by KirstieJane** [comment]
This makes sense to me! Happy to hear others' opinions though!

The main BIDS spec has some phase images in it already (for the field maps) so we'd just need to find where exactly makes sense to add that information.

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#two-phase-images-and-two-magnitude-images

**Comment by Gilles86** [comment]
See https://github.com/bids-standard/bep001/commit/d6bab3b4d4b9c9898d0756e73a008cddfe272c21 for a proposal

**Comment by Gilles86** [comment]
Reworked this to a [pull request](https://github.com/bids-standard/bep001/pull/17) based on @agahkarakuzu's work.

**Comment by Gilles86** [comment]
(I think I need to do this again, rebased on the current `master`-branch.)

**Comment by Gilles86** [comment]
https://github.com/bids-standard/bep001/pull/39
