### ISSUE TITLE
Notes from Sept 4 call, plan for Sept 18 call

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#70]
### Call on 4 September 2019

* @agahkarakuzu apologises for not updating the inheritance principle as planned - he's going to keep working on #59 & tag in @KirstieJane for a review
* we made a few small fixes and merged a couple of PRs
* @lazaral is going to keep working on #38 including making sure that the inheritance principle isn't violated (ie: one json file per nifti file).

### Next call: 18 September 2019

The next call is on 18 September at 8am PDT / 10am EDT / 3pm BST / 4pm CEST.

Here's a link to get your local time: https://arewemeetingyet.com/London/2019-09-18/15:00/BEP001%20dev%20call

We haven't been really explicit about the metadata fields that have to accompany certain qMRI acquisitions. **That's our goal for the next call**.

* @lazaral is going to work on getting the hMRI demo dataset into BIDS format (https://github.molgen.mpg.de/hMRI-group/Toolbox/wiki/HmriDemoDataset)
* @Gilles86 is going to bring MP2RAGE example data that can be made public
* @agahkarakuzu will bring anything he can
* @ChristophePhillips, if you're around, it would be great to have an update on your work updating the hMRI toolbox

**Comment by ChristophePhillips** [comment]
Hi,
Yes I will be around and this time it's penned in my agenda.
And I should have the list of meta-data used by the hMRI toolbox by then. :-)
FYI with guys from Leipzig (Tobias Leutritz and Daniel Rose), we are also working on converting the hMRI example dataset into BIDS. Could be an idea to join our effort, @lazaral ?
Best.

**Comment by KirstieJane** [comment]
That's amazing @ChristophePhillips!! Thank you so much!

**Comment by lazaral** [comment]
That's great, thank you @ChristophePhillips  ! Happy to have a look at your example BIDS or to have a first go and then send it over, whichever works best for you :)
