### ISSUE TITLE
November call

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#74]
Hi folks! I can't remember if we set a time for the next call 🤦‍

The next Wednesday at 4pm (UK) that I'm available is November 13. Shall we do that? 

Alternatively I could do Tuesday 5 November at 4pm (UK)?

Can you react to this issue with a 🚀 for 5 November and 👀 for 13 November? (You can respond twice) and I'll go with the majority ✨

**Comment by tiborauer** [comment]
I can join on 13th but not on 5th.

**Comment by KirstieJane** [comment]
Lets go with 13 November! I'll send an email now 😄
