### ISSUE TITLE
ISMRM Abstract | Action required from co-authors

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#75]
Hi BEP001 folks!

@agahkarakuzu has written a really fantastic abstract to present BEP001 at ISMRM in 2020.

The link to the text is here: https://docs.google.com/document/d/1b-mbpHbVckd53jXfQR4mSZ_wBxqy_AdwTxkKP0HUKyg/edit?usp=sharing

We've put the following authors on the document - please add your affiliations and comment here if you're ok with being named on the abstract.
- [x] @agahkarakuzu 
- [x] @Gilles86 
- [x] @sappelhoff (BIDS maintainer)
- [x] @tiborauer 
- [x] @mathieuboudreau
- [x] @franklin-feingold (BIDS maintainer)
- [x] @akhanf
- [x] @lazaral 
- [x] @ChristophePhillips 
- [x] @nstikov
- [x] @KirstieJane 

@effigies & @chrisgorgo - would you like to be in the list? We're not sure what you'd prefer and you're very welcome!

**If you are not named and think you should be please let me know!** @Gilles86 and I have a very strong inclusion policy! We're very sorry if we've forgotten you 😭 

I think we're slightly over the word count at the moment but @Gilles86 and I figured there was no point in getting it absolutely perfect before you had the chance to comment 😆 

*Having said that....*

The submission deadline is 6 November but the real deadline is this Sunday 3 November due to scheduling challenges next week. So please have a look through as quickly as possible - thank you so much 💖

**Comment by effigies** [comment]
I don't think I've contributed significantly to BEP001, but I appreciate the offer.

**Comment by tiborauer** [comment]
Tibor Auer, University of Surrey, Guildford, UK

**Comment by tiborauer** [comment]
I love Figure 3! It is a concise summary of the concept.

**Comment by sappelhoff** [comment]
very cool, thanks for preparing this!

**Comment by franklin-feingold** [comment]
thank you for including me! looks really good and the figures are very clear!

**Comment by KirstieJane** [comment]
Zooming! Thank you everyone - I think we have all of your affiliations! WAY TO GO! 🎉 

There's only one substantial comment in the document about linking with other similar initiatives. We mention the ISMRM Raw Data Standard but @Gilles86 and I don't know the others 😬 

If you have sugestions of ones to add then we're happy to add them, but my suspicion is that we can't get that information done in time for the deadline - it's a great point for consideration going forwards though!

**Comment by ChristophePhillips** [comment]
Following this ISMRM abstract, should we be considering a similar (albeit much shortened) for OHBM?
[Submission](https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=3947) deadline is on December 19.
