### ISSUE TITLE
OHBM abstract | Deadline Dec 19

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#76]
As suggested by @ChristophePhillips in https://github.com/bids-standard/bep001/issues/75#issuecomment-549262868 we should submit an abstract to OHBM 2020.

@Gilles86 has said that he can make a shortened version of the doc - stay tuned here for a version of the ISMRM abstract. **Update** here it is! https://docs.google.com/document/d/1Zwg_dpwkk9YJzHU3wAV8jPvCZ9MUMCtgepee4ATx4hE/edit?usp=sharing

ACTIONS

* Please check the author list and comment here if anyone is missing who should be included
* Please have a read through of the abstract and add comments and suggestions....but if you want to _add_ something please suggest somewhere to ✂️ cut ✂️ too because we're very close to the 4000 character word limit.
* All authors, please make an account at the OHBM abstract submission page: https://ww4.aievolution.com/hbm2001. 
  * This might feel strange strange because it means clicking the "submit here" button at the bottom of [this page](https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageID=3944&activateFull=true). You aren't going to submit anything, you're just making it easier for @Gilles86 to submit next week!
* Please comment on this post whether you're planning to be at OHBM in person or not 👋 

Please add the 🚀 reaction to this post when you've made your account and the ❤️ reaction when you're happy with the abstract!

Thank you @Gilles86 and @agahkarakuzu for writing it!!

**Comment by lazaral** [comment]
Isn't the deadline for OHBM abstracts on December 19? I just read the title of the issue and had a mini-panic :)

**Comment by ChristophePhillips** [comment]
If you're ready for the 1st, you will for the 19th... ;-)
I corrected the date though.

**Comment by Gilles86** [comment]
I made a first draft. Looking for feedback!

https://docs.google.com/document/d/1Zwg_dpwkk9YJzHU3wAV8jPvCZ9MUMCtgepee4ATx4hE/edit?usp=sharing
