### ISSUE TITLE
Validator rules for example datasets

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#79]
In #59 @agahkarakuzu has written the following table & explanatory text:

Although there is not an upper limit to the amount of metadata
for images collected by a `grouping suffix`, some of the metadata entries become
REQUIRED when considered within the context of a specific qMRI
application.

> _Table of method-specific priority levels for qMRI metadata_
> 
> | Grouping suffix             | REQUIRED `varying` metadata fields   | OPTIONAL `varying` metadata fields | REQUIRED `constant` metadata fields | OPTIONAL `constant` metadata fields |
> | :-------------------------- | :---------------- | :--------------| :--------------| :--------------|
> | VFA                         | FlipAngle         |    - | SequenceType, RepetitionTimeExcitation | PhaseIncrement|
> | IRT1                        | InversionTime     |     - | -| - |
> | MP2RAGE                     | FlipAngle, InversionTime |  EchoTime | RepetitionTimeExcitation, RepetitionTimePreperation | |
> | MESE                        | EchoTime         |   - | - | -|
> | MEGRE                       | EchoTime         |   - | - | -|
> | MTR                         | MTState         |     - | - | - |
> | MTS                         | FlipAngle, MTState  | - | RepetitionTimeExcitation| - |
> | MPM                         | FlipAngle, MTState, EchoTime, RepetitionTimeExcitation |  - | - | - |
> 
> Explanation of the table:
> 
> * The metadata fields listed in the REQUIRED columns are needed to perform a
> minimum viable qMRI application for the corresponding `grouping suffix`.
> * Note that some of the metadata fields may be unaltered across different members
> of a given `grouped scan collection`, yet still needed as an input to a qMRI
> model for parameter fitting. These fields are listed under the
> `REQUIRED constant metadata fields` column.
> * The `REQUIRED varying metadata fields ` column lists metadata entries that are
> subjected to at least one change across the members of a given
> `grouped scan collection` and needed as an input for parameter fitting.
> * The metadata fields listed in the OPTIONAL columns can be used to derive
> different flavors of the minimum viable qMRI application for the respective
> `grouping suffix`. The following section expands on the set of rules governing
> the derivation of qMRI applications from an existing `grouping suffix`.

This prompted @Gilles86 & me to think about what the rules need to be for the validator for different suffices. 

My opinion is that it isn't very helpful to separate the metadata into required and optional and varying and constant. Better to just focus on what would be REQUIRED.

@lazaral and @ChristophePhillips - we had a look at some of the MPM datasets in https://osf.io/k4bs5 and got kinda confused 😬 Do you think it might be possible to harmonise those in advance of next Wednesday's meeting (#74, 13 Nov)? I think it would be really helpful to continue the editing of #59 to get it merged to master ✨ 

Thank you again everyone for your awesome work 💪

**Comment by lazaral** [comment]
Sure - some is still in progress (I've been away for the past two weeks and back later this week) but I'll sort it out before the next meeting.

**Comment by ChristophePhillips** [comment]
Yes, I've got a few "free days" to re-focus on the MPM data before next meeting.
@lazaral, let's sort this out! :-)

**Comment by lazaral** [comment]
I pushed this a bit forward, I think we are nearly there with the MPM dataset (although it may change depending on the #73 discussion)
