### ISSUE TITLE
April 2020 meeting?

### ISSUE THREAD

**Issue by lazaral** [bids-standard/bep001#87]
Hi everyone - I just realised we haven't had one of our Wednesday meetings in a _very_ long time!

I am currently stuck at home and realised I have potentially some extra free time I could spend on BEP001. I'm also aware not everyone will be in the same situation, but thought I'd post an issue in case others were keen to start regular BEP001 calls again?

Reply with 
:rocket: if you are up for meeting next week and do some BEP001 work or with 
:scream_cat: if you are feeling overwhelmed with the amount of virtual coffees you're having in a day and would rather pause BEP001 until lockdowns are over.

**Comment by ChristophePhillips** [comment]
I assigned the "usual suspects" but feel free to poke-tag others. 😄 

And I hope that all of you are safely at home dealing with the exceptional conditions!
