### ISSUE TITLE
Include additional metadata fields 

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#9]
From August call:

**Suggestion from CP (for MPM & hMRI toolbox):**
- Got a list of stuff to add and have provisionally inserted them in BEP001 document… may not be entirely related to MT scans. 
- Here they are
- MixingTime (TM) in seconds. 
- In a STEAM (Stimulated Echo Acquisition Mode) experiment, three consecutive RF pulses are applied to generate a simulated echo (STE). The mixing time is the time interval between the second and third pulses. [Ref: Frahm J, Merboldt KD, Hänicke W, Haase A. Stimulated echo imaging. J Magn Reson 1985;64:81-93] 
- RFSpoilingPhaseIncrement.
- in RF-spoiled gradient echo sequences (e.g. FLASH), RFSpoilingPhaseIncrement (in degrees) is the increase in the phase difference between consecutive pulses. This parameter, together with the spoilingGradientMoment and the spoilingGradientDuration, is required to calculate imperfect spoiling correction coefficients (Preibisch & Deichmann 2009). If not available, no imperfect spoiling correction will be applied. 
- spoilingGradientMoment. 
- in gradient-spoiled gradient echo sequences (e.g. FLASH), spoilingGradientMoment is the zeroth moment (in T*s/m) of the spoiler gradient applied at the end of each repetition. This parameter, together with the RFSpoilingPhaseIncrement and the spoilingGradientDuration, is required to calculate imperfect spoiling correction coefficients (Preibisch & Deichmann 2009). If not available, no imperfect spoiling correction will be applied.
- spoilingGradientDuration: 
- in gradient-spoiled gradient echo sequences (e.g. FLASH), spoilingGradientDuration is the duration (in s) of the spoiler gradient applied at the end of each repetition. For a trapezoidal gradient, the duration is defined as the ramp-up duration + flat-top duration. This parameter, together with the RFSpoilingPhaseIncrement and the spoilingGradientMoment, is required to calculate imperfect spoiling correction coefficients (Preibisch & Deichmann 2009). If not available, no imperfect spoiling correction will be applied.

**Suggestion from AKar**

- MT Pulse shape (eg. gaussian, gaussian-hann, fermi, etc)
- Duration of the MT pulse 
- Bandwidth of the MT pulse 
- Off-resonance frequency of the MT pulse 
- Spoiler gradient moment between the MT pulse and the readout

**Comment by Gilles86** [comment]
Contact Christophe Phillips (CP) and Agâh Karakuzu (AKar) for a draft of the piece of text that would go into the final spec?

**Comment by Gilles86** [comment]
I think this has not been adressed in any of the current pull requests. I don't think this is in my area of expertise. @agahkarakuzu? Does Christophe Phillips have Github ID?

**Comment by agahkarakuzu** [comment]
@Gilles86 this one went through the cracks, happy to start working on this after tomorrow's meeting. Another discussion that relates to this was having method-specific priority levels for metadata fields, if the idea sounds reasonable to the majority, I can draft that one as well. 

> Does Christophe Phillips have Github ID? 

I don't know.

**Comment by Gilles86** [comment]
@agahkarakuzu, any news?

**Comment by agahkarakuzu** [comment]
@Gilles86, my answer to this will be quite relevant to your comment about being proactive in #19.

I could not do anything so far, but I will work on this today as much as I can to prepare a draft.

**Comment by Gilles86** [comment]
Awesome!

**Comment by agahkarakuzu** [comment]
@Gilles86 here is the markdown for all the additional metadata fields (but the mixing time) mentioned in this issue:

https://github.com/agahkarakuzu/bep001/blob/addmetadata/additional_metadata.md

**Comment by Gilles86** [comment]
All these things have been included in the main branch by @agahkarakuzu now.
